# Generated by Django 5.0.6 on 2024-06-10 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Useraccount', '0002_profile_start_date_alter_profile_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=100)),
                ('email', models.EmailField(default='default@example.com', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='start_date',
        ),
    ]
